// Mocks generated by Mockito 5.4.4 from annotations
// in social_network/test/features/users/users_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:social_network/app/data/models/user_api_model.dart' as _i2;
import 'package:social_network/app/data/repository/user_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserApiResponseModel_0 extends _i1.SmartFake
    implements _i2.UserApiResponseModel {
  _FakeUserApiResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  @override
  _i4.Future<_i2.UserApiResponseModel> getUsers({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.UserApiResponseModel>.value(
            _FakeUserApiResponseModel_0(
          this,
          Invocation.method(
            #getUsers,
            [],
            {#page: page},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.UserApiResponseModel>.value(
            _FakeUserApiResponseModel_0(
          this,
          Invocation.method(
            #getUsers,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.UserApiResponseModel>);
}
