name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Cria um arquivo .env a partir do exemplo antes de rodar os comandos do Flutter.
      # Isto resolve o erro "asset file '.env' doesn't exist".
      - name: Create .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
